services:
    # lightninglabs/bitcoin-core is the base image for bitcoind.
    # The environment variables default values determined on stage of container
    # start within starting script.
    bitcoind:
        image: bitcoind
        container_name: bitcoind
        build:
            context: bitcoind/
        environment:
            - RPCAUTH
            - NETWORK
            - BITCOIND_DEBUG
            - PS1=root@bitcoind#
        volumes:
            - bitcoin:/data
        entrypoint: ["./start-bitcoind.sh"]
    lnd:
        image: lnd
        container_name: lnd
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd
            - PS1=\u@lnd#
        volumes:
            - lnd:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd1:
        image: lnd
        container_name: lnd1
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd1
            - PS1=\u@lnd1#
        volumes:
            - lnd1:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd2:
        image: lnd
        container_name: lnd2
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd2
            - PS1=\u@lnd2#
        volumes:
            - lnd2:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd3:
        image: lnd
        container_name: lnd3
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd3
            - PS1=\u@lnd3#
        volumes:
            - lnd3:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd4:
        image: lnd
        container_name: lnd4
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd4
            - PS1=\u@lnd4#
        volumes:
            - lnd4:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd5:
        image: lnd
        container_name: lnd5
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd5
            - PS1=\u@lnd5#
        volumes:
            - lnd5:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd6:
        image: lnd
        container_name: lnd6
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd6
            - PS1=\u@lnd6#
        volumes:
            - lnd6:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd7:
        image: lnd
        container_name: lnd7
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd7
            - PS1=\u@lnd7#
        volumes:
            - lnd7:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd8:
        image: lnd
        container_name: lnd8
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd8
            - PS1=\u@lnd8#
        volumes:
            - lnd8:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd9:
        image: lnd
        container_name: lnd9
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd9
            - PS1=\u@lnd9#
        volumes:
            - lnd9:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd10:
        image: lnd
        container_name: lnd10
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd10
            - PS1=\u@lnd10#
        volumes:
            - lnd10:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd11:
        image: lnd
        container_name: lnd11
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd11
            - PS1=\u@lnd11#
        volumes:
            - lnd11:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd12:
        image: lnd
        container_name: lnd12
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd12
            - PS1=\u@lnd12#
        volumes:
            - lnd12:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd13:
        image: lnd
        container_name: lnd13
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd13
            - PS1=\u@lnd13#
        volumes:
            - lnd13:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

    lnd14:
        image: lnd
        container_name: lnd14
        build:
            context: ../
            dockerfile: dev.Dockerfile
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
            - NETWORK=regtest
            - CHAIN=bitcoin
            - LND_DEBUG=debug
            - BACKEND=bitcoind
            - ALIAS=lnd14
            - PS1=\u@lnd14#
        volumes:
            - lnd14:/root/.lnd
        entrypoint: ["./start-lnd.sh"]
        depends_on:
            - "bitcoind"
        links:
            - "bitcoind:blockchain"

volumes:
    bitcoin:
        driver: local
    lnd:
        driver: local
    lnd1:
        driver: local
    lnd2:
        driver: local
    lnd3:
        driver: local
    lnd4:
        driver: local
    lnd5:
        driver: local
    lnd6:
        driver: local
    lnd7:
        driver: local
    lnd8:
        driver: local
    lnd9:
        driver: local
    lnd10:
        driver: local
    lnd11:
        driver: local
    lnd12:
        driver: local
    lnd13:
        driver: local
    lnd14:
        driver: local
